version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "javascript"
